name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: change dir
      run: cd third_party
    - name: get_atl
      run: ./get_atl.sh
    - name: move
      run:   ../ 
    - name: make atl
      run:  make
